### ISSUE TITLE
Feature Request: Informix Support

### ISSUE THREAD

**Issue by qbradq** [hioa-cs/IncludeOS#1027]
I am looking into C++ as a development platform for my company. A key reason for this is our move to a microservice architecture has seen the memory overhead of Java become a Big Problem™. This is what brings me to IncludeOS as a very self-contained and memory efficient application container.

Most of our persistence layer uses IBM's Informix database. And as business software most of what we do is execute SQL queries. So I'd like to know:

1. What is the roadmap toward SQL vendor support in general?
2. Where does IBM Informix fit into those plans?
3. If I were to begin work on a PR to add Informix support, where would I begin? Can someone give me a vision of what it would look like?

Thank you

Edit: A free developer edition of Informix can be downloaded here:http://www-03.ibm.com/software/products/en/infodeveedit

**Comment by ingve** [comment]
Hi! Thank you for looking at IncludeOS!

There are a lot of SQL (and NoSQL) database vendors, so I'm not sure there will be support for all of them directly in the OS, but IncludeOS already supports most of C/C++, and POSIX support is currently being implemented, so our hope is to have enough functionality/plumbing to enable the community to add support for their favourite database solutions, for example by porting existing open source C/C++ database connectivity libraries.

I am no expert when it comes to Informix specifically, but if there are any open source C/C++ database drivers, you could try porting one of those to IncludeOS. Otherwise, you could write an IncludeOS service that speaks one of the client protocols Informix supports for network communication with TCP/IP.

**Comment by qbradq** [comment]
@ingve Thank you for your response! I thought this was the case. Want to get the fastest "No" you've ever heard? Here was a portion of my conversation with the IBM rep:

"Do you provide driver source..."
"**NO**"

My company does not typically invest in things like developing database drivers from scratch. It's just not a good fit for our business. We are looking at bringing other persistence technologies to the deployment platforms I am particularly interested in, all of which are open-source or have open-source drivers. I will look in that direction.

As far as porting an existing database driver to IncludeOS, would I just need to convert the blocking I/O operations to IncludeOS asynchronous I/O? Are there any other concerns or pointers you can call out?

Thank you again.

**Comment by ingve** [comment]
Converting the blocking I/O operations to IncludeOS-style async I/O would be the best solution.

However, in the next release of IncludeOS, which is just around the corner, there will be partial POSIX support, including some traditional-style socket functions (check out the `dev` branch to see what is already there).
