### ISSUE TITLE
Make Connection write and read virtual

### ISSUE THREAD

**Issue by themodder666** [hioa-cs/IncludeOS#1078]
I would like these methods to be made virtual, so that you can have derived classes override them and provide alternate functionality (in my case a TLS Connection).

**Comment by themodder666** [comment]
Also do you guys have a slack or discord? I dislike putting all this stuff into issues lol.

**Comment by ingve** [comment]
We have a Gitter chat, come join us there!

https://gitter.im/hioa-cs/IncludeOS

**Comment by fwsGonzo** [comment]
We've decided to do something like this, but it might just be a layer on top of Connection where there is some object that implements just enough stuff to cover both TLS and non-TLS streams. The reason is because TLS streams don't have all the options that normal TCP streams have, and they also have some extra requirements.

Feel free to chime in with a proposal in our channel, of course

**Comment by AndreasAakesson** [comment]
`net::Stream` is now added, which kinda solves the issue. Thanks for your suggestion 👍
