### ISSUE TITLE
Missing 'elf_syms' and 'vmbuild' on clean build

### ISSUE THREAD

**Issue by Arxcis** [hioa-cs/IncludeOS#1385]
>>> Done! IncludeOS bundle downloaded and installed

>>> Building chainloader
~/Documents/code/IncludeOS/src/chainload/build ~/Documents/code/IncludeOS
-- Building for arch i686, platform x86_nano
-- CMake root: /usr/local
-- Target CPU architecture i686
-- Target triple i686-pc-linux-elf
-- Using vanilla CPU features: SSE3. CAPABS = -msse3 -mfpmath=sse
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jsolsvik/Documents/code/IncludeOS/src/chainload/build
[ 25%] Linking CXX executable chainloader
[100%] Built target service
make[2]: /usr/local/includeos/bin/elf_syms: No such file or directory
make[2]: /usr/local/includeos/bin/vmbuild: No such file or directory
make[2]: *** [CMakeFiles/pruned_elf_symbols] Error 1
make[1]: *** [CMakeFiles/pruned_elf_symbols.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/prepend_bootloader] Error 1
make[1]: *** [CMakeFiles/prepend_bootloader.dir/all] Error 2
make: *** [all] Error 2
>>> Sorry <<<
Could not build chainloader.

**Case**
I built IncludeOS normally, but with the wrong $INCLUDE_PREFIX. It led to filepaths beiing /usr/local/includeos/includeos/bin which led to errors. I could not run the ./test.sh successfully.

So I decided to do a "clean-buildl" whatever that is. I removed all contents of  the /usr/local/includeos/bin directory, including elf_syms and vmbuild. Then I tried to build agian, but now the build script is complaining that elf_syms and vmbuild is missing. I thought the install.sh would take care of these dependencies, as it did the first time I built IncludeOS. How to I do a completely clean build? I haven't found any guides on that.

**Comment by mnordsletten** [comment]
Hi

The best way to ensure a completely clean build is to remove your build folders and run `install.sh` again. The build folders are located at `$INCLUDEOS_SRC/build_$ARCH`, there should be one called `build_x86_64` and one called `build_i686`. 

The error you got is due to the vmbuild and elf_syms being external projects and they don't correctly detect that their output was deleted. This is an error and will get fixed. 

Thanks for reporting, hope this helps.
