### ISSUE TITLE
Can I use third party lib in IncludeOS?

### ISSUE THREAD

**Issue by Vxider** [hioa-cs/IncludeOS#1546]
Hi:
    I'm a beginner of Unikernel and I want to migrate my App to IncludeOS. But I have use some 3rd libs like folly, boost and zmq. Is IncludeOS support these 3rd libs?

**Comment by ingve** [comment]
You can use many 3rd party libs with IncludeOS, see the [SQlite demo service](https://github.com/hioa-cs/IncludeOS/tree/dev/examples/SQlite) for an example. If the libraries you want to use depend on pthreads you might run into some issues since this part of IncludeOS is still WIP. 

Regarding boost, it depends on what parts of boost you want to use. For example, I use [Boost CRC](http://www.boost.org/doc/libs/1_65_1/libs/crc/crc.html) in a test service, and that works as expected, but there are probably some other libraries in Boost that will be slightly more challenging to get to work.

If you decide to try migrating your app to IncludeOS and run into any issues with any third-party libraries, feel free to file issues here or come into our [gitter chat](https://gitter.im/hioa-cs/IncludeOS)

**Comment by Vxider** [comment]
Thanks, I'll try it.
