### ISSUE TITLE
Cannot ping from inside the unikernel

### ISSUE THREAD

**Issue by jbarraca** [hioa-cs/IncludeOS#1753]
I've created an unikernel that only prints it's network interface and pings a remote host (my laptop). The printf works fine but the unikernel does not ping the host.
The cpp code is bellow:
![image](https://user-images.githubusercontent.com/33351821/39177347-f9a73218-47a6-11e8-9d4f-fd27b7bd1c40.png)

when i do the ping from my laptop it works (tcpdump from bridge43, bridge that connects the unikernel to its host): 
![image](https://user-images.githubusercontent.com/33351821/39177674-cc82cb84-47a7-11e8-9b8a-83340cb3ce49.png)

**Comment by AndreasAakesson** [comment]
Hey! I looked into your issue. The reason this is happening is because your passing the IP address as a string.

First of all - can you verify that this snippet works if you replace it: `inet.icmp().ping(inet.gateway());` (this works for me).

Pinging with a string results in a DNS resolve as seen in `icmp4.cpp`:
```
  void ICMPv4::ping(IP4::addr ip)
  { send_request(ip, ICMP_type::ECHO, 0); }

  void ICMPv4::ping(IP4::addr ip, icmp_func callback, int sec_wait)
  { send_request(ip, ICMP_type::ECHO, 0, callback, sec_wait); }

  void ICMPv4::ping(const std::string& hostname) {
    inet_.resolve(hostname, [this] (IP4::addr a, Error err) {
      if (!err and a != IP4::ADDR_ANY)
        ping(a);
    });
  }
```

I'm running dnsmasq on my host so it the string variant do work for me as well.
Wireshark:
>26	09:23:25.850603	10.0.0.42	10.0.0.1	DNS	68	Standard query 0x0001 A 10.0.0.1
27	09:23:25.850679	10.0.0.1	10.0.0.42	DNS	84	Standard query response 0x0001 A 10.0.0.1 A 10.0.0.1
28	09:23:25.853385	10.0.0.42	10.0.0.1	ICMP	90	Echo (ping) request  id=0x0000, seq=0/0, ttl=64 (reply in 29)
29	09:23:25.853397	10.0.0.1	10.0.0.42	ICMP	90	Echo (ping) reply    id=0x0000, seq=0/0, ttl=64 (request in 28)

**Comment by AndreasAakesson** [comment]
I guess we could consider having our own DNS client check if the string is an IP address before trying to resolve, and if it is, just return the parsed IP. But I can't say if this is weird behavior or not(?).

**Comment by fwsGonzo** [comment]
Seems fine to me, will simplify many instances of code that doesn't need to be fast
