### ISSUE TITLE
etc/install_osx.sh requires clang++-3.6 but does not make sure it's there

### ISSUE THREAD

**Issue by kybeg** [hioa-cs/IncludeOS#319]
I'm trying to use the IncludeOS installscript from etc/install_osx.sh on El Capitan with Xcode version 7.1.1

Towards the end I'm getting the following errors: 

clang++-3.6 -target i686-elf -mrdrnd -msse3 -mstackrealign -O2 -DNO_DEBUG=1 -Wall -Wextra  -c -m32 -std=c++14 -fno-stack-protector -I../api/sys -I/Users/kyrre/IncludeOS_install/libcxx/include  -I/Users/kyrre/IncludeOS_install/newlib/include  -Iinclude -I../api  -D_LIBCPP_HAS_NO_THREADS=1 -DOS_VERSION="\"v0.7.0-proto-8-g3da1bf2\""  -x assembler-with-cpp crt/crti.s -o crt/crti.o
/bin/sh: clang++-3.6: command not found
make: *** [crt/crti.o] Error 127
~/work/IncludeOS

There is no clang++-3.6 on my system. Do I neet to install it from somewhere else?

**Comment by alfred-bratterud** [comment]
Hi, yes, you can install it with brew - the script should probably be updated to do that, since it's a mac script. @AndreasAakesson you agree?  This being said, I think we should try to move to cmake sooner rather than later, in order to have a more portable solution.

**Comment by kybeg** [comment]
What package in particular installs clang++-3.6? llvm? I’ll write this up as a howto once I have it working.

**Comment by AndreasAakesson** [comment]
Hey. I was thinking about putting llvm 3.6 as a dependency, tho its not small (almost 500mb installation). Easiest way to install is with [homebrew](http://brew.sh/); `brew install llvm` (this will be latest, 3.6, I think) or `brew install llvm36`.

I tried to symlink the brew installation, `/usr/local/Cellar/llvm/3.6.2/bin/clang++`, to `clang++-3.6`, without success.. This could be one solution, since it will also work on all the Makefiles for examples/tests.

@alfred-bratterud if you think adding brew and llvm36 as an dependency to do script is a good idea I can add it. I think it's a an OK solution - it will make the installation longer but less painless.

**Comment by alfred-bratterud** [comment]
We're allready installing all the Ubuntu dependencies so until we can switch to something more robust, like cmake, I think specialized but complete solutions are better than partial solutions.

**Comment by AndreasAakesson** [comment]
Fixed in #332

**Comment by alfred-bratterud** [comment]
Great!
