### ISSUE TITLE
High performance capture from network

### ISSUE THREAD

**Issue by pavel-odintsov** [hioa-cs/IncludeOS#325]
Hello, Team!

Great project! Thanks so much! Brilliant idea and awesome implementation with best ever language!

I'm author of high performance network analyzer and I'm thinking about support of IncludeOS: github.com/pavel-odintsov/fastnetmon

And I'm interested in fast packet capture from virtio network driver and further processing inside IncludeOS VM.

So I want to ask. Is my idea weird or songs possible? :) I have huge list of supported capture engines (netmap, af_packet, pf_ring, pcap, SnabbSwitch) and have almost complete network stack implementation for my purposes and I could implement it for raw virtio.

**Comment by alfred-bratterud** [comment]
Hi @pavel-odintsov, thanks a lot! 
Capturing packets in IncludeOS is exceptionally simple; each network object in IncludeOS is connected via a simple delegate - all you have to do is to is to set the network upstream delegate from the Virtio-device, to poin to your own function / member function / lambda. If you want to keep the packets going on the usual path, you then have your own function, just call the function originally pointed to by the delegate when you're done. I just made a simple example of how to do this a couple of days ago, here:
https://github.com/hioa-cs/IncludeOS/blob/dev/src/debug/test_service.cpp#L59

As for the further challenges you'll face if you want to support existing code is a question of how many dependencies your code has. If you can manage with standard C- and C++ libraries, without filesystem and threads, you'll probably be fine. Otherwise, please let us know what your dependencies would be, and we'll answer any questions as best we can. 

Again thanks for the feedback - it's really much appreciated!

**Comment by pavel-odintsov** [comment]
Thanks for detailed explanation! :) I could drop almost all my dependencies and C++ 11 is enough for me. But I need fast way to query time really fast (few million times per second) and rdtsc do this job with flying colors! 

I'm using this code right now:
```C++
inline uint64_t rte_rdtsc(void) {
    union {
        uint64_t tsc_64;
            struct {
                uint32_t lo_32;
                uint32_t hi_32;
            };  
    } tsc;

    asm volatile("rdtsc" :
        "=a" (tsc.lo_32),
        "=d" (tsc.hi_32));
    return tsc.tsc_64;
}
```

Do you have something like this? With this fast timers I could emulate timer behavior.  Actually I need threads support but I read about lack of their support. 

But my idea behind threads deeply related with load balancing.

I need some way to spread incoming packets across multiple threads because single thread could not process they. My idea is really similar to Linux's SO_REUSEPORT capability. And this approach could remove threads support from requirements! :) 

Also I'm thinking about really_fast way to drop packets to VM from hardware NIC and folks from SnabbSwitch offered great solution: https://github.com/SnabbCo/snabbswitch/issues/674

**Comment by alfred-bratterud** [comment]
Hi, we use `rdtsc` for all time-measurments as well, see [`uint64_t OS::cycles_since_boot`](https://github.com/hioa-cs/IncludeOS/blob/master/api/kernel/os.hpp#L50). 

When it comes to proper timers, we've only implemented a ~1ms resolution timer based on the PIT-chip. (The API is [here](https://github.com/hioa-cs/IncludeOS/blob/master/api/hw/pit.hpp), the implementation [here](https://github.com/hioa-cs/IncludeOS/blob/master/src/hw/pit.cpp) ). 

I guess if you don't mind spending a lot of CPU cycles for polling, you could probably do a spinwait solution which would probably be the fastest way possible on a single thread. You'd have to get very close to virtio, though; the normal virtio operation is to wait for the device to signal an interrupt, but interrupts always cause VM exit. It might be possible to poll the [virtio ring directly](https://github.com/hioa-cs/IncludeOS/blob/master/api/virtio/virtio.hpp#L215), to instantly detect updates - but you really have to consult the virtio standard closely to get that right. An idea for the spinwait solution is to use our ~ms timer to abort the spinning if there haven't been any packets for a while. Then your CPU load would be pretty much 100% on traffic, otherwise 0%. 

We're very interested in getting high performance networking in IncludeOS, so please keep us posted!

**Comment by alfred-bratterud** [comment]
Also note: I see Snabbswitch is using hugepages - that's not going to be necessary in IncludeOS where we have no virtual memory. However, page alignment is still going to have a big impact on performance inside the virtual guest, so it helps to know the page size and allocate memory pools on page borders. I.e. `memalign(4096, ...)` gives much better performance than `malloc` on certain cache intensive memory tests for normal sized pages.
