### ISSUE TITLE
Boot options

### ISSUE THREAD

**Issue by kybeg** [hioa-cs/IncludeOS#335]
Any chance IncludeOS could get boot options, where command-line options are passed on to a buffer in the OS by the bootloader? This would enable feature flags as well as debugging and some flexibility without recompiling and re-uploading images everywhere.

**Comment by alfred-bratterud** [comment]
Good question!  If you want data into the disk image (bootloader or otherwise) you'll have to 
* A) Rebuild the image (you don't necessariliy have to recompile, but you'll have to rerun vmbuilder)
* B) Implement support for secondary hard drives, and have a separate drive for configuration. Ubuntu cloud images can be set up this way. 
* C) Pass in the data through a I/O-channel, such as serial port or TCP. 

I think B) I think we'll definitely do this as a part of the read-only file system we're working on. This way can easily reattach a drive also with new data, such as HTML/Javascript/CSS etc. for static web content. I think we should make this a priority for the next couple of months A) Is in the works, with our read-only file system C) is probably the simplest solution in the short term. Set up something like a puppet master, listening on TCP, and have the VM connect to there for any configuration or data. 

As a C2-option, you could route the serial port to a network interface from the outside, and let the VM read from the serial port. This is really easy with Qemu, but I'm less sure about virtualbox.

**Comment by kybeg** [comment]
I guess this also depends on what the virtualization platform offers.

OpenStack has something that solves C, namely the metaserver, where the virtual machines can get loads of info about themselves, including boot options (more user-space options, really). So as long as one has a http client inside IncludeOS, one could at least use the metaserver for parameterization of instances.

**Comment by alfred-bratterud** [comment]
I think the FAT-based memory-disk is now the way to go. See #364 for an example!

**Comment by fwsGonzo** [comment]
Boot options can now be passed to the VM via the bootpy program, however, there are no facilities for command-line arguments for any other platform. Simply no support.
