### ISSUE TITLE
Test OS components in isolation

### ISSUE THREAD

**Issue by matiashf** [hioa-cs/IncludeOS#341]
This might include individual components of the IP stack. The objective here would be to run unit tests outside a virtual machine.

**Comment by fwsGonzo** [comment]
We could test the network stack with a Linux Tap device from outside, by feeding packets from the tap device into the bottom of the stack.

**Comment by alfred-bratterud** [comment]
Yes @fwsGonzo - that's the right way to test the full stack. Actually, that's the way to use the IncludeOS stack as a fully functional userspace stack, without passing through the linux one. 

For unit testing however, it's also probably desirable to test one class at a time. But: we have two types of classes inside the kernel: 
* **Type 1: pure logic** - these have simple data in / data out interfaces, which are easy to unit test outside of IncludeOS. All the network stack objects are (should be) pure logic. (The nic driver, VirtioNet, is not in the stack, but below it). We should definitely be able to use google test to test these for logic errors, robust handling of corner cases where the input packet is garbage or zero etc. We would just have to set up mock-objects above and below,with the proper delegate signatures to feed packets through it. 
* **Type 2: hardware huggers**, i.e. classes that directly interact with hardware.  IRQ-manager, PCI manager, virtionet etc. are hardware-huggers, and these are impossible to unit test in userspace Linux because they often call privileged instructions, usually `out` / `in`, or also write to explicit addresses (i.e. memory mapped PCI devices)

In principle I'm very much for doing unit tests where possible, but then mainly on classes that have had stable interfaces for a while - there aren't too many of those yet (otherwise we'll just have twice as much code to rewrite every time we refactor / change the API).  That being said: Our hardest bugs come from hardware-huggers - I've never spent as long debugging as when virtionet worked perfectly in Qemu but not at all in virtualbox - it literally took weeks. 

Since unit tests are all about assertions, I think maybe a good starting point for us, which we can use pretty much in every function everywhere, would be to use [Expects](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Ri-expects) and [Ensures](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Ri-ensures). My only issue with the [GSL](https://github.com/Microsoft/GSL) implementation is that I can't see how to completely deactivate them, for production. This might be so by design, but even if it's just a few cycles pr. assertion in a lot of cases, I can easily dream up cases where they could be quite heavy. So I'd definitely like to be able to switch them off completely, i.e. make them preprocessed out.

My vote goes to starting with including GSL into IncludeOS, and start implementing pre- and postconditions in a lot of places first with GSL (after we figure out a good way to disappear them completely without modifying GSL). Then we can move on to full unit-testing. Thoughts?

**Comment by fwsGonzo** [comment]
Ok, but there is only one GSL implementation by Microsoft, and it will have to support clang.. does it?

**Comment by matiashf** [comment]
@fwsGonzo: Yes, [Microsoft GSL](https://github.com/Microsoft/GSL) supports GNU/Linux and Windows using Clang/LLVM 3.6. On OS X Yosemite the clang compiler in XCode is required.

**Comment by matiashf** [comment]
@alfred-bratterud I agree, assertions should be the first priority, and Unit tests should be implemented when the API has stabilized. Testing Kernel IO is, for now, probably sufficiently covered by functional tests using the example services.

GSL assertions *can* be disabled completely by building with the flag [GSL_UNENFORCED_ON_CONTRACT_VIOLATION](https://github.com/Microsoft/GSL/blob/master/include/gsl_assert.h#L70). This uses preprocessor macros to disable Expects and Ensures, and should not introduce any overhead. Or have I missed something?

When building for debugging or testing we should define GSL_THROW_ON_CONTRACT_VIOLATION. This will make failed assertions throw an exception.

TODO:
1. GSL assertions (with zero overhead in production builds)
2. Units tests of isolated components using mock objects

**Comment by fwsGonzo** [comment]
:+1:

**Comment by alfred-bratterud** [comment]
Aha, missed that one - great! @fwsGonzo according to the readme GSL is tested - by Microsoft -  with clang 3.6 on Linux. I had to blink twice to make sure I was actually reading that correctly :-)

**Comment by alfred-bratterud** [comment]
@fwsGonzo @AndreasAakesson and @matiashf Check out @RicoAntonioFelix [http-module](https://github.com/RicoAntonioFelix/IncludeOS-HTTP-Service), where he's using a header-only test framework called [Catch](https://github.com/philsquared/Catch). Anybody wants to volunteer to try this inside IncludeOS? At a glance the dependencies seem to be only `sstream`, `stdexcept` and `algorithm`, which should be fine. At least let's discuss using Catch vs. Goole test.

**Comment by marssaxman** [comment]
Is the goal specifically to run unit tests outside the VM, or to have an automated mechanism for validating/debugging low-level system components? Have you considered using the emulator debug port (0xE9)?

**Comment by alfred-bratterud** [comment]
@marssaxman I wasn't aware of that port, but looking into it I think that's what we're using when we have gdb connect with qemu, which works well - when you get it up and running it's just like running the debugger on a normal userspace process.  When it comes to unit tests / assertions etc. I'm thinking that output from could probably just be written to standard out, which would then end up going out the serial port, which you can then route into a file, socket or pipe on the host. Then we'll have to figure out how to make some test runner start vm's with different unit tests in them, for the stuff that can't be tested independently outside - like Rico is doing with the http module.  I'll first take steps to hook up GSL into IncludeOS (sort out include paths etc.) and then I'll look into Catch, if / when I can.

**Comment by alfred-bratterud** [comment]
I've now successfully integrated lest into the tests (e3f91a8d6a8f381a3ab1b586581676b0de9171d7), which seems to work nicely. Still some work to be done to make an external testrunner combine internal tests and external verifications.
