### ISSUE TITLE
RFC: Docker image for IncludeOS builder

### ISSUE THREAD

**Issue by kybeg** [hioa-cs/IncludeOS#358]
Hello, 

I've made a docker image called kybeg/includeos-build that will do the compilation and image building in an IncludeOS project. This means that in order to compile (not run) a IncludeOS image, you only have to install docker and then pull the image. This should allow a greater independence from the underlying platform you're on. 

I'm currently basing it on the releases of IncludeOS, but can also build them with custom versions. The uploaded version in docker hub is based on the v0.7.0-proto source tree.

Could any of the developers test if it works for them?

To install run the following: 

apt-get install docker.io
docker pull kybeg/includeos-build:v0.3-includeos-v0.7.0-proto

To use the compiler enter the seed directory you're working on and run:

docker run  -v $(pwd):/tmp/seed kybeg/includeos-build:v0.3-includeos-v0.7.0-proto

In order to streamline things, you can create an alias:

alias includeos-build="docker run --rm -v \$(pwd):/tmp/seed kybeg/includeos-build:v0.3-includeos-v0.7.0-proto"

I used a modified install-from-bundle.sh script that skips the qemu installation when creating the docker image. If this works out, I can send a pull request with it to the dev branch.

**Comment by alfred-bratterud** [comment]
Really cool that you're working on this - will be looking forward to trying it out!

**Comment by alfred-bratterud** [comment]
PS: This should definitely be a topic on devel.unikernel.org - would be interesting to hear if any other unikernel projects are doing it similarly.

**Comment by mjbright** [comment]
Any progress on this?

Would be nice to see a github repo with at least a Dockerfile, and IncludeOS 0.10 ...

**Comment by ingve** [comment]
We haven't published any new containers in the Docker Registry since there are so many different workflows, depending on whether you want to use a Docker container to develop and rebuild the core IncludeOS library, or if you want to work on and rebuild a specific IncludeOS service that is in development, or if you want to build and deploy a finished IncludeOS service.

For the last use case, there is a Docker image in the [UniK](https://github.com/emc-advanced-dev/unik) platform.

There is also a Dockerfile in the main IncludeOS github repo, but this is designed for an in-tree-like workflow where you use your local, already cloned IncludeOS installation.

If you are looking for a "no install" workflow like the one Kyrre described in this thread, I have updated our Dockerfiles to use IncludeOS 0.10.0 and put them up in a new GitHub repo:

https://github.com/includeos/includeos-docker-images

If you can give me some more information about what kind of workflow you have in mind, we can probably improve our Docker support even further, so let us know what you need, here or in our [gitter chat](https://gitter.im/hioa-cs/IncludeOS)!

**Comment by alfred-bratterud** [comment]
See this repo for dockerfiles: https://github.com/includeos/includeos-docker-images
