### ISSUE TITLE
Make install script more robust

### ISSUE THREAD

**Issue by ingve** [hioa-cs/IncludeOS#620]
Currently, the install script spews a lot of output as it is downloading and building IncludeOS, and no matter what goes wrong, the script valiantly trudges on. If there is a networking issue during the download phase, the script will still run to completion and claim that installation is done, even if it was unable to build os.a and copy it to the destination directory. With hundreds of lines of output to scroll through, it can be difficult to identify the problem.

Would it be possible to have some basic sanity checking in the install script? After installing dependencies, check that they can in fact be run? After building os.a and friends, check that they actually exist before outputting the "installation done" message, etc.

**Comment by fwsGonzo** [comment]
We could download the checksum files also and validate all the downloads, although it would make the install process a little bit longer.

**Comment by andreashappe** [comment]
The cmake-based download+build has support for checksum verification (mostly, so that fiels will not be downloaded again and again).

But I've only tested it with Fedora (Linux), no virtual network device is created (yet) and some stuff is missing. But it might be fixable before the next release.

HTH
