### ISSUE TITLE
seed/run.sh should not require an argument

### ISSUE THREAD

**Issue by matiashf** [hioa-cs/IncludeOS#623]
When using the seed project, `run.sh` must be called with the argument `IncludeOS_service.img`. However, if called with `IncludeOS_service`, qemu is started and does nothing, but doesn't provide an error message. This is very confusing. The default `run.sh` implementation should **not** require any arguments to run.

**Comment by AndreasAakesson** [comment]
Not sure how easy this is since the script (qemu) needs to know what image to run. On some of our services/examples, we have put this inside the local `run.sh`, but this is not the case when making a seed.
One solution could be to (hopefully) some day make a tool that helps out with a lot of stuff, like for example creating a memdisk or a new named seed service.

**Comment by fwsGonzo** [comment]
Feel free to take charge and make the necessary changes to show the proper error when missing an argument to run.sh etc.

**Comment by AndreasAakesson** [comment]
A solution to the problem:
Makefile
```
export INC_SERVICE_IMAGE=$(SERVICE).img
```
seed/run.sh
```
# if parameter passed to script - use it
# else if INC_SERVICE_IMAGE defined - use it
# else - continue as usual
```
