### ISSUE TITLE
Heap debugging

### ISSUE THREAD

**Issue by fwsGonzo** [hioa-cs/IncludeOS#826]
Adding debugging versions of new, delete, malloc and free would trivialize problems like the stress test showing the heap not returning to a pre-set size.

This work was already started, but complicated due to having to also implement debug versions of shared and unique ptr.

**Comment by gurka** [comment]
Why do you have to add debug versions of new, delete, shared/unique_ptr? What do you want to accomplish? Shouldn't it be enough to override/ "hijack" malloc and free, since new/delete uses them internally?

In another project I've worked with a tool that we used to track memory leaks and other types of memory errors while running in "semi-production". The tool overrides malloc and free and can be started/stopped at any time. The work flow when looking for memory leaks is something like:

1. Start application with memory guard built in and let it execute to some initial state.
2. Start memory guard
3. Do something with the application that _should not_ make the heap usage increase (e.g. start some subservice and then stop it, going back to the initial state).
4. Stop the memory guard
5. Tell memory guard to print all allocations that were made from point 2 which haven't been free'd yet, including a stack trace for each allocation (so that you can see where the allocations were made). These are possible memory leaks. 

The tool can also check, automatically, for write overflow/underflow by allocation a larger buffer than requested and inserting checksums before/after the buffer and verifying that the checksums are correct when the buffer is free'd. It can also check for allocations of zero bytes, double free(), and so on.

Shouldn't it be possible to use a similar tool for IncludeOS?

**Comment by fwsGonzo** [comment]
thats fine and all, and yes I could do that in 10 minutes
but I want to pass along filenames, line numbers and caller (using backtrace), so that the heap tables have more than just the address and length as information :)

to do that we also have to deal with shared and unique ptrs, passing stuff along with that... not so easy :(

so yes, we could track malloc and free, but anyone can do that when they need it :)
i want to make something that is more useful, but i dont know enough about C++ *_ptr internals yet

**Comment by gurka** [comment]
Aha, I understand. The tool I worked with stored a stack trace for each allocation that were made. So by using a script on the output together with an unstripped object file you were able to get function names and approximate line number (or rather, how "far" into the function the call was made from. `((return_adress - function_adress) / function_length) * 100` ). After using the script you got output like:

> Possible memory leak, 54 bytes allocated at:
> Foo::allocate() (40%)
> Foo::Foo() (15%)
> Bar::createFoo() (90%)
> ...
>
> Possible memory leak, 128 bytes allocated at:
> ...

**Comment by fwsGonzo** [comment]
I have made an attempt in my dev branch: https://github.com/fwsGonzo/IncludeOS

It's fairly shaky right now because of all the no-heap stuff :) but it does work, and I caught 2 errors with it.
