### ISSUE TITLE
macOS: unnecessary binutils tar ball in IncludeOS_build

### ISSUE THREAD

**Issue by shekhar108** [hioa-cs/IncludeOS#881]
After extracting the binutils tar, there is no reason to keep the tar ball.

```
    diff --git a/etc/install_osx.sh b/etc/install_osx.sh
index 51b89e9..33e7a2e 100755
--- a/etc/install_osx.sh
+++ b/etc/install_osx.sh
@@ -17,7 +17,6 @@ INCLUDEOS_BUILD=${INCLUDEOS_BUILD-$HOME/IncludeOS_build}
 INCLUDEOS_INSTALL_LOC=${INCLUDEOS_INSTALL_LOC-$HOME}
 INCLUDEOS_INSTALL=${INCLUDEOS_INSTALL-$INCLUDEOS_INSTALL_LOC/IncludeOS_install}

-
 echo -e "\n###################################"
 echo -e "IncludeOS installation for Mac OS X"
 echo -e "###################################"
@@ -59,7 +58,6 @@ function install_llvm {
     echo -e "\n>>> Done installing: llvm"
 }

-
 ## BINUTILS ##
 echo -e "\nbinutils (ld, ar, objcopy, strip) - required for building IncludeOS"
 DEPENDENCY_BINUTILS=false
@@ -120,6 +118,7 @@ function install_binutils {
     ## Clean up
     echo -e "\n> Cleaning up..."
     rm -rf $INCLUDEOS_BUILD/$BINUTILS_RELEASE
+    rm -rf $INCLUDEOS_BUILD/$filename_binutils

     ## Copy LD
     echo -e "\n> Copying linker ($BINUTILS_LD) => $LD_INC"

```

**Comment by AndreasAakesson** [comment]
Yeah, I agree! The reason the tar ball isn't cleaned up is old. It was because when something in the script failed, we would like to avoid downloading it once more when reinstalling. But whats more correct would be to at the end, if everything is ok (no trap), remove the `IncludeOS_build` all together - this is not needed since the binaries are copied to `IncludeOS_install/bin`. The directory could just be temporary inside the repository - no need to put it in home `~/`.

**Comment by shekhar108** [comment]
Thanks for the insight. I agree with your design decision.
It just happened that you updated the binutils version in the install script and when I installed again I had two tar balls (old version and new version).
This seems like a minor problem though. I will see if I can come up with a solution.

**Comment by AndreasAakesson** [comment]
With the new version introduced in https://github.com/hioa-cs/IncludeOS/pull/956 it no longer remains any files if the installation is successful. Binutils is now also globally installed.
