### ISSUE TITLE
elf_syms seg faulting

### ISSUE THREAD

**Issue by geisler** [hioa-cs/IncludeOS#963]
I'm trying to create a very simple service as a hello world to start from.  When using the Makefile from the demo_service example, everything seems to work until it calls elf_syms on the generated binary.  The seg fault is in line 94 (the one that calls `strlen(org)`).  My guess is that `org` isn't null-terminated, but I don't know enough about ELF formatted files to trace this down.  I would attach a copy of the binary if I could figure out how to do that inside GitHub.  What should I try to help debug the system?

**Comment by fwsGonzo** [comment]
The elf symbol names (strings) are plain C null-terminated strings. If strlen fails somehow, the problem is earlier, like something is wrong with the symbol structures. Or there is some special case where the symbol name is zero or something. Maybe that's it.

**Comment by fwsGonzo** [comment]
So to summarize: Try skipping a symbol if its name field is 0. On line 80, add the test `if (cursym.st_name != 0)`, and see if that works

**Comment by geisler** [comment]
That didn't make a difference.  I'll dig more and report back, but finals are coming up, so it will probably be slow slogging for the next couple weeks for me. :(

**Comment by fwsGonzo** [comment]
Ok, that's too bad then :) GL with the finals

**Comment by szborows** [comment]
@geisler @fwsGonzo
I've stumbled on this problem as well on my x86_64 debian:testing box (clang-3.9!). This is what I've found:

- the problem is not with not \0-terminated string. it's rather with invalid memory access
`#1  0x0000000000401274 in relocate_pruned_sections (new_location=0x614c20 "\f$\255\373\270\v", symtab=..., strtab=...) at elf_syms.cpp:98`
`98          size_t      len = strlen(org) + 1;`
`(gdb) print org`
`$1 = 0x7ffff7fdd379 <error: Cannot access memory at address 0x7ffff7fdd379>`
- while doing hello world program bundled with IncludeOS I get very strange value for strtab.size:
`(gdb) print strtab.size`
`$2 = 163`
this is kind of suspicious to me, because `readelf -S IncludeOS_service` gives me
`[18] .strtab           STRTAB          00000000 0e85b4 03420a 00      0   0  1`
`213514` is definitely greater than `163`
- however, accidentally I found one entry below with size `a3 (= 163)`:
`[19] .shstrtab         STRTAB          00000000 11c7be 0000a3 00      0   0  1`
i believe this is the culprit, because for loop in `elf_syms.cpp` isn't prepared for duplicated sections.

Following diff seem to have worked, but it's definitely not state-of-the-art solution. I'm going to do a little more research on the subject so maybe I will come up with proper solution soon.

```
diff --git a/vmbuild/elf_syms.cpp b/vmbuild/elf_syms.cpp
index 6a2ac80..320b87c 100644
--- a/vmbuild/elf_syms.cpp
+++ b/vmbuild/elf_syms.cpp
@@ -123,8 +123,10 @@ static void prune_elf_symbols()
                         shdr[i].sh_size / (int) sizeof(Elf32_Sym) };
       break;
     case SHT_STRTAB:
-      strtab = StrTab { (char*) elf_offset(shdr[i].sh_offset),
+      if (!strtab.base) {
+        strtab = StrTab { (char*) elf_offset(shdr[i].sh_offset),
                         shdr[i].sh_size };
+      }
       break;
     case SHT_DYNSYM:
     default:
```

**Comment by fwsGonzo** [comment]
Ok, I know what the problem is then.. I'll probably just be selecting the first strtab I find and then replace it with a bigger one if that happens. That will "always" work. :)

Thanks for the info :+1:

**Comment by szborows** [comment]
> That will "always" work. :)
can you please elaborate on this? :)

**Comment by fwsGonzo** [comment]
The only issue is maybe that we don't really detect if the image is tripped. There will always be a string table, and its the one that has the table names.

```
diff --git a/vmbuild/elf_syms.cpp b/vmbuild/elf_syms.cpp
index 6a2ac80..b2fae3c 100644
--- a/vmbuild/elf_syms.cpp
+++ b/vmbuild/elf_syms.cpp
@@ -123,8 +123,10 @@ static void prune_elf_symbols()
                         shdr[i].sh_size / (int) sizeof(Elf32_Sym) };
       break;
     case SHT_STRTAB:
-      strtab = StrTab { (char*) elf_offset(shdr[i].sh_offset),
-                        shdr[i].sh_size };
+      // select the biggest strtab
+      if (shdr[i].sh_size > strtab.size)
+        strtab = StrTab { (char*) elf_offset(shdr[i].sh_offset),
+                          shdr[i].sh_size };
       break;
     case SHT_DYNSYM:
```

**Comment by alfred-bratterud** [comment]
@fwsGonzo close? And @szborows thanks for the fix!
