### ISSUE TITLE
Compiler

### ISSUE THREAD

**Issue by qis** [hioa-cs/IncludeOS#988]
It should be possible to chose a compiler version when invoking `install.sh`. In particular, I would like to test IncludeOS with Clang 4.0.0 that is already installed on the system instead of working with an outdated Clang 3.8.

**Comment by fwsGonzo** [comment]
So do we, but operating systems are complicated. We have to use a complete toolchain with everything working together perfectly. We want to use clang 4.0 too, but if we do that we have to install it manually with the OS so that older and current linux distributions have the same toolchain.

Also, clang 4.0 is still in beta, so we may still want to wait for the official release anyways.

**Comment by qis** [comment]
How about giving an option to skip the compiler installation then? Let the user define CC and CXX or some IncludeOS specific environment variables.

**Comment by alfred-bratterud** [comment]
Hi @qis, for Linux targets you could try adding clang 4.0 to the list in [install_from_bundle](https://github.com/hioa-cs/IncludeOS/blob/dev/etc/install_from_bundle.sh) which is what `install.sh` ends up calling, and see if it works. The script will try to find the newest of the clang versions we know should work, regardless of what the dependency script installed (since that script has to install the best option available from the platforms package manager).
You could also call `install_from_bundle.sh` directly to skip  the installation of the dependencies (just note the required env vars at the top). As you can see that script actually checks if `CXX`/`CC` is already set and if so try and use that before building the os.

**Comment by fwsGonzo** [comment]
I have tried to compile the project with Clang 5.0 (trunk), and it worked fine for me. Just to update you, there was no issue at all. I just set CC and CXX to the new compiler from trunk, and it all went swimmingly.

**Comment by qis** [comment]
@fwsGonzo Thanks for the tip. Did it also use the new libcxx version?

**Comment by fwsGonzo** [comment]
No, that needs to be ported. They always change things, and it will take some time to do, fully integrating it into the OS again.

**Comment by fwsGonzo** [comment]
We are using libc++ 3.9 now, and I'm still using trunk so it's at least newer now.. maybe next time we will go for 4.0.
